<a href="https://colab.research.google.com/github/Ishani-Patel/data690_fall2022/blob/main/assignment_05/part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 

In [8]:
import numpy as np

In [9]:

a = np.array([1,2,3])

In [10]:
a[0], a[1], a[2]

(1, 2, 3)

In [11]:
a[0:-1]

array([1, 2])

In [12]:
a[[0,2]]

array([1, 3])

In [13]:
a = np.array([1, 2, 3, 4])


In [14]:
a.dtype


dtype('int64')

In [15]:
b = np.array([0, .5, 1, 1.5, 2])


In [16]:
b[[0, 2, -1]]


array([0., 1., 2.])

In [17]:
b.dtype


dtype('float64')

In [18]:
c = np.array(['a', 'b', 'c'])


In [19]:
c.dtype


dtype('<U1')

In [20]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [21]:
A.shape


(2, 3)

In [22]:
A.ndim


2

In [23]:
A.size


6

In [24]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [25]:
C.dtype


dtype('O')

In [26]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [27]:
A[1]

array([4, 5, 6])

In [28]:
A[1][0]


4

In [29]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
A[:, :2]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [31]:
A[:2, 2:]

array([[3],
       [6]])

In [32]:
A[1] = np.array([10, 10, 10])

In [33]:
A


array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [34]:
A[2] = 99


In [35]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [36]:
a = np.array([1, 2, 3, 4])

In [37]:
a.sum()


10

In [38]:
a.mean()


2.5

In [39]:
a.std()

1.118033988749895

In [40]:
a.var()

1.25

In [41]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [42]:
A.sum()

45

In [43]:
A.mean()

5.0

In [44]:
A.std()

2.581988897471611

In [45]:
A.sum(axis=0)

array([12, 15, 18])

In [46]:
A.sum(axis=1)

array([ 6, 15, 24])

In [47]:
A.mean(axis=0)

array([4., 5., 6.])

In [48]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [49]:
a = np.arange(4)

In [50]:
a

array([0, 1, 2, 3])

In [51]:
a[0], a[-1]

(0, 3)

In [52]:
a[[0, -1]]

array([0, 3])

In [53]:
a[[True, False, False, True]]

array([0, 3])

In [54]:
a >= 2

array([False, False,  True,  True])

In [55]:
a[a >= 2]

array([2, 3])

In [56]:
a.mean()

1.5

In [57]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [58]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [59]:
A = np.random.randint(100, size=(3, 3))

In [60]:
A

array([[87, 49, 37],
       [89, 66, 50],
       [53, 34, 87]])

In [61]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([87, 37, 66, 53, 87])

In [62]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [63]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [64]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [65]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [66]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [67]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [68]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])